<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>&quot;The Greenbone Vulnerability Manager Service is not responding&quot;</title>
    <meta name="article-id" content="ka04u000000HdBWAA0">
    <meta name="articlecaseattachcount" content="0">
    <meta name="articlecreatedbyid" content="0054u000006god6AAA">
    <meta name="articlecreateddate" content="2022-02-07T01:03:08.000Z">
    <meta name="articlenumber" content="000008323">
    <meta name="createdbyid" content="0054u000006god6AAA">
    <meta name="createddate" content="2023-05-08T10:18:23.000Z">
    <meta name="firstpublisheddate" content="2022-02-07T01:03:08.000Z">
    <meta name="islatestversion" content="true">
    <meta name="knowledgearticleid" content="kA04u0000000JhHCAU">
    <meta name="knowledge-article-id" content="kA04u0000000JhHCAU">
    <meta name="lastmodifiedbyid" content="0054u000006gSmgAAE">
    <meta name="lastmodifieddate" content="2023-05-08T10:18:23.000Z">
    <meta name="lastpublisheddate" content="2022-02-07T01:03:08.000Z">
    <meta name="meta-description" content="HELPDESK">
    <meta name="meta-title" content="&quot;The Greenbone Vulnerability Manager Service is not responding&quot;">
    <meta name="ownerid" content="0054u000006god6AAA">
    <meta name="recordtypeid" content="0124u000000UUgLAAW">
    <meta name="urlname" content="8323">
    <meta name="versionnumber" content="1">
    <meta name="website-url" content="&lt;a href=&quot;https://helpcenter.netwrix.com/bundle/z-kb-articles-salesforce/page/kA04u0000000JhHCAU.html&quot; target=&quot;_blank&quot;&gt;Open in a new window&lt;/a&gt;">
</head>
<body>
    <h1>&quot;The Greenbone Vulnerability Manager Service is not responding&quot;</h1>
    <p><strong><u>Issue:</u></strong></p><p><strong>&quot;The Greenbone Vulnerability Manager Service is not responding&quot;</strong></p><p><strong><u>Cause:</u></strong></p><ul><li><p>VM may be running under an unsupported Greenbone Hypervisor. For this example, the GSM VM was running using <strong>QEMU (KVM).</strong></p></li><li><p>I/O errors were found in the file system using the <strong>\support-package\gsm-support\kernel-journal</strong> file. Example below:</p></li></ul><blockquote><p><em>2020-12-21 10:20:17.194858: : kernel[]: err: ata1.00: status: { DRDY ERR }</em><br><em>2020-12-21 10:20:17.194906: : kernel[]: err: ata1.00: error: { ABRT }</em><br><em>2020-12-21 10:20:17.194986: : kernel[]: info: ata1.00: configured for MWDMA2</em><br><em>2020-12-21 10:20:17.195042: : kernel[]: info: ata1.01: configured for MWDMA2</em><br><em>2020-12-21 10:20:17.195086: : kernel[]: info: sd 0:0:0:0: [sda] tag#0 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE</em><br><em>2020-12-21 10:20:17.195991: : kernel[]: info: sd 0:0:0:0: [sda] tag#0 Sense Key : Illegal Request [current]</em><br><em>2020-12-21 10:20:17.197487: : kernel[]: info: sd 0:0:0:0: [sda] tag#0 Add. Sense: Unaligned write command</em><br><em>2020-12-21 10:20:17.197914: : kernel[]: info: sd 0:0:0:0: [sda] tag#0 CDB: Write(10) 2a 00 01 a6 43 a0 00 08 c0 00</em><br><em>2020-12-21 10:20:17.198373: : kernel[]: err: print_req_error: I/O error, dev sda, sector 27673504</em><br><em>2020-12-21 10:20:17.198419: : kernel[]: warning: EXT4-fs warning (device dm-0): ext4_end_bio:323: I/O error 10 writing to inode 62 (offset 0 size 0 starting block 3327604)</em><br><em>2020-12-21 10:20:17.198471: : kernel[]: err: Buffer I/O error on device dm-0, logical block 3327604</em><br><em>2020-12-21 10:20:17.198566: : kernel[]: err: Buffer I/O error on device dm-0, logical block 3327605</em><br><em>2020-12-21 10:20:17.198624: : kernel[]: err: Buffer I/O error on device dm-0, logical block 3327606</em><br><em>2020-12-21 10:20:17.198669: : kernel[]: err: Buffer I/O error on device dm-0, logical block 3327607</em><br><em>2020-12-21 10:20:17.198714: : kernel[]: err: Buffer I/O error on device dm-0, logical block 3327608</em><br><em>2020-12-21 10:20:17.198760: : kernel[]: err: Buffer I/O error on device dm-0, logical block 3327609</em><br><em>2020-12-21 10:20:17.198811: : kernel[]: err: Buffer I/O error on device dm-0, logical block 3327610</em><br><em>2020-12-21 10:20:17.198856: : kernel[]: err: Buffer I/O error on device dm-0, logical block 3327611</em><br><em>2020-12-21 10:20:17.198916: : kernel[]: err: Buffer I/O error on device dm-0, logical block 3327612</em><br><em>2020-12-21 10:20:17.198977: : kernel[]: err: Buffer I/O error on device dm-0, logical block 3327613�</em></p><p><em>2020-12-19 22:15:47.633328: </em><a class="external-link" href="mailto:postgresql@11-main.service" target="_blank"><em>postgresql@11-main.service</em></a><em>: postgres[23761]: info: [7-1] 2020-12-19 22:15:47.633 UTC [23761] LOG:� database system was interrupted; last known up at 2020-12-19 22:05:14 UTC</em><br><em>2020-12-19 22:16:07.015776: </em><a class="external-link" href="mailto:postgresql@11-main.service" target="_blank"><em>postgresql@11-main.service</em></a><em>: postgres[23761]: info: [8-1] 2020-12-19 22:16:07.015 UTC [23761] LOG:� database system was not properly shut down; automatic recovery in progress</em><br><em>2020-12-19 22:16:07.181292: </em><a class="external-link" href="mailto:postgresql@11-main.service" target="_blank"><em>postgresql@11-main.service</em></a><em>: postgres[23761]: info: [9-1] 2020-12-19 22:16:07.168 UTC [23761] LOG:� redo starts at 3E/227BFBE8</em><br><em>2020-12-19 22:17:49.167039: </em><a class="external-link" href="mailto:postgresql@11-main.service" target="_blank"><em>postgresql@11-main.service</em></a><em>: postgres[23761]: info: [10-1] 2020-12-19 22:17:49.166 UTC [23761] LOG:� redo done at 3E/3AE8FFB0</em><br><em>2020-12-19 22:17:49.168735: </em><a class="external-link" href="mailto:postgresql@11-main.service" target="_blank"><em>postgresql@11-main.service</em></a><em>: postgres[23761]: info: [11-1] 2020-12-19 22:17:49.167 UTC [23761] LOG:� last completed transaction was at log time 2020-12-19 22:15:24.311144+00</em><br><em>2020-12-21 10:20:17.199068: </em><a class="external-link" href="mailto:postgresql@11-main.service" target="_blank"><em>postgresql@11-main.service</em></a><em>: postgres[573]: info: [4-1] 2020-12-21 10:20:17.185 UTC [573] LOG:� WAL writer process (PID 632) was terminated by signal 6: Aborted�</em></p></blockquote><p><strong><u>Resolution:</u></strong></p><ul><li><p>Ensure that the GSM VM is running on a supported Greenbone Hypervisor (<a class="external-link" href="https://supportnntws.atlassian.net/l/c/ow2b8968" target="_blank">LINK</a>) using the Greenbone Support Package</p></li></ul><p style="margin-left: 60.0px;"><em>\support-package\gsm-support\kernel-journal</em></p><p style="margin-left: 60.0px;"><em>Line: kernel[]: info: Hypervisor detected: <strong><span style="color: rgb(255,86,48);">--HYPERVISOR--</span></strong></em></p><ul><li><p>If the GSM VM is supported (hypervisor) but in an �undefined state�, forward support package to Greenbone support.</p></li><li><p>If the GSM VM is both unsupported (hypervisor) and in an �undefined state�, the GSM VM will need to be completely rebuilt. In this situation, do not export/import any data from the problematic system into the new system.</p></li></ul>
</body>
</html>